# Generated by Django 3.2.6 on 2021-08-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
